### ISSUE TITLE
BUG: codegen panics with `Error("missing field `description`", line: 0, column: 0)`

### ISSUE THREAD

**Issue by buhaytza2005** [sreeise/graph-rs-sdk#478]
**Describe the bug**

**To Reproduce**
1. Create `test.rs` file in `examples` - as per codegen wiki with the following content:
```rust
use graph_codegen::openapi::OpenApi;

fn main() {
    let open_api = OpenApi::default();
    open_api.debug_path_contains("solutions");
}
```
2. run the file `cargo run --example test`
3. panics in `either_t.rs`:
```bash
     Running `target/debug/examples/test`
thread 'main' panicked at graph-codegen/src/openapi/either_t.rs:83:54:
called `Result::unwrap()` on an `Err` value: Error("missing field `description`", line: 0, column: 0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
**Expected behavior**
List out the paths that contain `solutions`

Adding a `println!` just before the unwrap on line 83, shows that there is an empty object in the response, hence the `description` key missing:
```rust
[...]
impl<'de, T: DeserializeOwned> Deserialize<'de> for EitherT<T, Reference> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value: serde_json::Value = Deserialize::deserialize(deserializer)?;
        let map = value.as_object().ok_or_else(|| {
            D::Error::custom(format!(
                "Expected struct matching either `T` or `Reference`. Found the following \
                 serde_json::Value:\n{value:#?}\n"
            ))
        })?;

        if map.contains_key("$ref") {
            let reference: Reference = serde_json::from_value(value).unwrap();
            Ok(EitherT::right(reference))
        } else {
            println!("{:#?}", value);
            let t: T = serde_json::from_value(value).unwrap();
            Ok(EitherT::left(t))
        }
    }
}
[...]
```
```bash
[...]
}
Object {
    "description": String("The unique identifier of authenticationEventsFlow"),
    "in": String("path"),
    "name": String("authenticationEventsFlow-id"),
    "required": Bool(true),
    "schema": Object {
        "type": String("string"),
    },
    "x-ms-docs-key-type": String("authenticationEventsFlow"),
}
Object {}
thread 'main' panicked at graph-codegen/src/openapi/either_t.rs:84:54:
called `Result::unwrap()` on an `Err` value: Error("missing field `description`", line: 0, column: 0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

An update was pushed to the Microsoft repo, perhaps something in the specification is causing this? 

<img width="560" alt="image" src="https://github.com/sreeise/graph-rs-sdk/assets/44904160/7735b02c-e52b-4470-856f-70710ea74503">

I don't understand enough about the inner workings of the crate to investigate further.

**Comment by sreeise** [comment]
Thanks for reporting this. This is kind of odd. I believe this is probably a case where a field was added to the OpenAPI schema. But I am not 100% sure. Because if im not mistaken the codegen has annotations for serde that tell it to ignore unknown fields but maybe we are missing one.

I'll have to investigate this further. Thanks for the report.
